# Generated by Django 3.1.6 on 2021-04-20 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FPS', '0002_auto_20210328_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='name',
            field=models.CharField(default='old data', max_length=10),
            preserve_default=False,
        ),
    ]
